# Generated by Django 2.1 on 2018-09-05 17:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('is_mine', models.BooleanField(default=False)),
                ('n_nearby_mines', models.IntegerField(default=0)),
                ('is_dug', models.BooleanField(default=False)),
                ('is_flagged', models.BooleanField(default=False)),
                ('is_marked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_name', models.CharField(max_length=30)),
                ('height', models.IntegerField(default=10)),
                ('width', models.IntegerField(default=10)),
                ('n_mines_all', models.IntegerField(default=8)),
                ('n_mines_left', models.IntegerField(default=8)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='brick',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mines_api.Game'),
        ),
    ]
